on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Publishing Tableau Workbook
    steps:
      - name: Building runner
        id: tableau_publish
        uses: KjellGeerts/tableau_workbook@main
        with:
          accessToken: ${{ secrets.TOKEN_VALUE }}